default: &default
  adapter: postgresql
  encoding: unicode
  # Replace 'rails_backend_development' and 'rails_backend_test' with your desired database names
  database: rails_backend_development
  username: postgres
  password: 123
  host: localhost

development:
  <<: *default

test:
  <<: *default