Greeting.create(message: "Hello, world!")
Greeting.create(message: "Bonjour, le monde!")
Greeting.create(message: "Hola, mundo!")
Greeting.create(message: "こんにちは、世界！")
Greeting.create(message: "안녕하세요, 세상!")